### ISSUE TITLE
按布署或同步，闪退

### ISSUE THREAD

**Issue by benojan** [osfans/trime#136]
我的手机信息是：
型号：vivo X3L
Android版本：4.3
处理器1.2GHz骁龙400四核
内核版本：3.4.0
-----------------------------
把别人编译好的bin放入rime文件夹是可以使用的。就是自己新的方案无法布署。

**Comment by osfans** [comment]
這要看日誌了。需要root一下才能看到，或者通過adb logcat查看。

**Comment by benojan** [comment]
装好了adb，啥命令查看？

**Comment by osfans** [comment]
出錯時，執行adb logcat，然後把log導出來。

**Comment by benojan** [comment]
全部导出好像很慢哪……有无只看trime的日志？

**Comment by osfans** [comment]
先開log，然後部署，然後看新出來的log，傳上來看看。

**Comment by xiaoqun2016** [comment]
vivo X3L配置不高，在部署超大词库时可能会失败。

**Comment by osfans** [comment]
看log都沒有走到部署，很奇怪。

**Comment by xiaoqun2016** [comment]
要不要用单线程版本部署试试？ 安卓4.3的多线程会不会不同……

**Comment by tigren** [comment]
Nexus 5，系统 6.0，sync 和 deploy 都闪退

不过这老手机了，性能太差。我自己在电脑上编译再传到手机上可以用

**Comment by tigren** [comment]
接上，电脑上编译的五笔库拷到手机上，切换 Schema 的时候报错
`
02-18 21:24:08.951 D/ConnectivityService(815): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 135]
02-18 21:24:08.981 I/native  (2030): I/engine.cc:121 updated option: soft_cursor
02-18 21:24:08.981 I/Rime    (2030): message: [option] soft_cursor
02-18 21:24:08.982 I/native  (2030): I/engine.cc:121 updated option: _horizontal
02-18 21:24:08.983 I/Rime    (2030): message: [option] _horizontal
02-18 21:24:08.984 D/AndroidRuntime(2030): Shutting down VM
02-18 21:24:08.985 E/AndroidRuntime(2030): FATAL EXCEPTION: main
02-18 21:24:08.985 E/AndroidRuntime(2030): Process: com.osfans.trime, PID: 2030
02-18 21:24:08.985 E/AndroidRuntime(2030): java.lang.RuntimeException: Unable to create service com.osfans.trime.Trime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at android.app.ActivityThread.-wrap4(ActivityThread.java)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at android.os.Looper.loop(Looper.java:148)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at java.lang.reflect.Method.invoke(Native Method)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
02-18 21:24:08.985 E/AndroidRuntime(2030): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at com.osfans.trime.Config.getColorObject(Config.java:350)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at com.osfans.trime.Config.getColorDrawable(Config.java:437)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at com.osfans.trime.Keyboard.<init>(Keyboard.java:128)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at com.osfans.trime.Keyboard.<init>(Keyboard.java:339)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at com.osfans.trime.KeyboardSwitch.reset(KeyboardSwitch.java:45)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at com.osfans.trime.KeyboardSwitch.<init>(KeyboardSwitch.java:37)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at com.osfans.trime.Trime.onCreate(Trime.java:219)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
02-18 21:24:08.985 E/AndroidRuntime(2030): 	... 9 more
02-18 21:24:09.017 I/OpenGLRenderer(815): Initialized EGL, version 1.4
`

**Comment by tigren** [comment]
呃，请无视我，发现是因为我的配置文件里面有行
 `us_keyboard_layout: true`
删掉这行再操作就好了 😅

**Comment by osfans** [comment]
最好不要用電腦上的bin，目前bin還不通用
