### ISSUE TITLE
部分应用中回车键发送、搜索等功能失效

### ISSUE THREAD

**Issue by Wenti-D** [osfans/trime#1502]
### 摘要 / Summary

在有「回车键直接发送」「回车键搜索」等类似功能的应用中（例如 QQ），最新的测试版按下回车后：
- 若所有字都上屏了，编码区是空的，就没反应；
- 若编码区有东西，则按下回车会「立马把编码上屏并立马发出去」（有点像快速按了两下回车）。

### 重现步骤 / Steps to Reproduce

1. 开启 QQ 的「回车键发送消息」；
2. 打点字；
3. 点回车，你会发现如上文所述。

### 预期行为 / Expected Behavior

回车键应该能行使「发送」「搜索」之类的功能，且有编码时不能多按。

### 附加信息 / Additional Context

其实这个问题在上上个测试版好像就有了。试了几个主题（包括自带的）都这样。

### 系统版本 / OS Version

HarmonyOS 4（Android 12 兼容）

### 应用版本 / App Version

v3.3.1-6-g951b441d-release

### 构建信息 / Build Information

构建者：Windy Deng
Git 仓库：https://github.com/osfans/trime.git
构建 Git 哈希：951b441dc4a7bdf599b3b4a9e3308bd26375efd7
构建时间：2024年11月5日 13:07:07

**Comment by amalgame21** [comment]
Same issue.
I use Trime to unlock the phone with password.
The Enter/Return button is not functioning as intended to "input" the password, instead It makes the input cursor jump back to the beginning of the line.

Android 15
Trime 3.3.1 from F-droid

It works fine in Trime 3.2.29
I haven't tested 3.3.0, because to me it was broken.

**Comment by yurocy** [comment]
在微信输入也遇到了，打了一半输入一个英文，按回车上屏，就直接发出去了
