### ISSUE TITLE
无法关闭英文模式句首自动大写

### ISSUE THREAD

**Issue by dramforever** [osfans/trime#680]
**Describe the bug**

`style/auto_caps: false` 也无法关闭英文模式句首自动大写

**To Reproduce**

在 `trime.custom.yaml` 中配置

```
patch:  
  "style/auto_caps": false
```

然后重启 Trime，切换到英文模式开始输入包含 `. ` 的文本

**Expected behavior**

句首不自动大写

**Log**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi 10 Lite Zoom
 - OS: Android 10
 - Version: 3.2.5
 - Theme: default

**Comment by tusooa** [comment]
跟这个 https://github.com/osfans/trime/issues/679 https://github.com/osfans/trime/issues/643 我感觉是同一个问题。

**Comment by Bambooin** [comment]
You can try the latest daily build, seem fix by #711

**Comment by deluxghost** [comment]
> You can try the latest daily build, seem fix by #711

No, this issue is untouched, and there are 2 problems need to be resolved

1. according to the config, `auto_caps` should have 3 valid value: `true`, `false` and `ascii`:

   https://github.com/osfans/trime/blob/6c8f0313f5b1523f31c97105d9f58c8c31ce5613/app/src/main/assets/rime/trime.yaml#L9

   but `isAutoCaps` is defined as a boolean here: 
 
   https://github.com/osfans/trime/blob/6c8f0313f5b1523f31c97105d9f58c8c31ce5613/app/src/main/java/com/osfans/trime/ime/core/Trime.java#L130

2. look at this condition `isAutoCaps || Rime.isAsciiMode()`:
   https://github.com/osfans/trime/blob/6c8f0313f5b1523f31c97105d9f58c8c31ce5613/app/src/main/java/com/osfans/trime/ime/core/Trime.java#L782-L787

   it's obvious, when `isAutoCaps == false`, it checks `isAsciiMode` due to the OR logic, but it should not

   the correct condition this line in pseudo code should be:
   
   ```java
   // if true/false/ascii are valid
   isAutoCaps == "true" || (isAutoCaps == "ascii" && Rime.isAsciiMode())
   // if only true/false are valid
   isAutoCaps == "true"
   ```

I don't have android develop environment set, I hope someone else can post a PR to fix that

**Comment by tusooa** [comment]
~~3~~ ~~4~~ 5个版本之后仍然没修。

**Comment by dramforever** [comment]
好像我在 FDroid 上更新后没问题了，不过我也没有仔细看配置什么的

**Comment by tusooa** [comment]
3.2.9上已经不能复现。可能已经修复了。如果修复了，维护者应该关闭这个issue。

**Comment by dramforever** [comment]
确认新版已经没有这个问题了
