### ISSUE TITLE
請問如何提升輸入法的反應速度

### ISSUE THREAD

**Issue by z-Wind** [osfans/trime#838]
**Describe the bug**
https://github.com/z-Wind/rime_settings
這是我的設定，但感覺上還是會 lag
尤其是 space 按太快時，懸浮窗口會殘留
請問有什麼方法可以改進呢？

另一款 LIME HD 的回饋感好很多，但自定性沒 Trime 的好
https://github.com/lime-ime/limeime
非常喜歡 Trime，感謝作者的無私分享

**Smartphone (please complete the following information):**
 - Device: 紅米Note 4X
 - OS: Android 11, LineageOS18.1
![image](https://user-images.githubusercontent.com/16359142/186349209-4806a76b-dd54-4fdf-ad2a-2c77ba61f90e.png)

**Comment by InfinityLoop1308** [comment]
It is hard to give your schema a try. However, the most general reason resulting in input lag is the complexity. For example, JiuGong schemas with simplified spelling will result in unbearable delays because there are too many valid candidates. Please check if this is your case. If it isn't, please feel free to ask more questions.

**Comment by z-Wind** [comment]
應該不是候選字太多的原因，我有錄了個影片，比較兩者的差異
https://user-images.githubusercontent.com/16359142/186558083-64e7d128-9e14-42ec-9fe7-6d0727fea8cd.mp4

在同文輸入法時，按下 a 到出現候選框會有些 delay
到最後時，幾乎同時按下 a & space 時，字有上屏，但懸浮窗口會殘留

換到萊姆時，按下 a 到出現候選框，會比較即時，甚至候選字還比同文多，也有關聯字

**Comment by InfinityLoop1308** [comment]
> 應該不是候選字太多的原因，我有錄了個影片，比較兩者的差異 https://user-images.githubusercontent.com/16359142/186558083-64e7d128-9e14-42ec-9fe7-6d0727fea8cd.mp4
> 
> 在同文輸入法時，按下 a 到出現候選框會有些 delay 到最後時，幾乎同時按下 a & space 時，字有上屏，但懸浮窗口會殘留
> 
> 換到萊姆時，按下 a 到出現候選框，會比較即時，甚至候選字還比同文多，也有關聯字

please try using the default schema and check if the problem exists. If no that may be the problem of your schema

**Comment by z-Wind** [comment]
可否麻煩您提供需要我測試的 default schema
因為同文並無預設的檔案，我是從其他地方抓的
我怕我們的認知檔案並不一樣，而會有所差異，感謝

**Comment by InfinityLoop1308** [comment]
> 可否麻煩您提供需要我測試的 default schema 因為同文並無預設的檔案，我是從其他地方抓的 我怕我們的認知檔案並不一樣，而會有所差異，感謝

Sorry, but actually there is a default schema. You can back up your rime folder and then install a fresh Trime to give it a try. I have  just tested it, and it works smoothly.
By backing up the folder, you will not lose your data if your schema's db is not table-db. After testing, you can switch it back.

**Comment by z-Wind** [comment]
不好意思，我重裝後，只能輸入英文，並無中文的部分
但我的問題是中文的候選框與輸入間有 delay
還是我該如何啟動中文呢？感謝

**Comment by InfinityLoop1308** [comment]
> 不好意思，我重裝後，只能輸入英文，並無中文的部分 但我的問題是中文的候選框與輸入間有 delay 還是我該如何啟動中文呢？感謝

Thanks for your patience. I am really sorry because the Trime I used for the last test is from Google store, and it is very outdated(3.1.3). There is not a default Chinese schema in 3.2.7.

I don't know when and why the default Chinese schema is removed, but I do think it is a bad idea.
Currently, I have nothing to do, as my schema is deeply modified and hard to provide to you. You can have a try with schemas provided in https://github.com/Bambooin/rimerc , which should be the one used by another maintainer.

Let me know if you still have problems using schemas from that repo. If that is the case, please contact Bambooin for further diagnose.

**Comment by z-Wind** [comment]
感謝您的耐心回答
我複製 common & luna_pinyin & trime 下的檔案到 rime
選擇方案部署，然後就不會停止了 Orz
一直都是正在部署...，過了十分鐘後我就強制重開機了

**Comment by InfinityLoop1308** [comment]
> 我複製 common & luna_pinyin & trime 下的檔案到 rime

Are you using the schema I posted before? If yes it may take long because there are too many dicts needed to be complied to binaries. You can try to modify `luna_pinyin.extended.dict.yaml` and remove most of extended dicts. This way it will consume less time.
Please let me know if the problem exists.

**Comment by z-Wind** [comment]
最後，我修改 luna_pinyin.extended.dict.yaml，只留下 luna_pinyin 才成功部署
狀況一樣，如影片

https://user-images.githubusercontent.com/16359142/186646611-c2f334a5-3f1c-4d41-9fa9-e8c0e5d72d6c.mp4

**Comment by InfinityLoop1308** [comment]
@Bambooin Do you have any idea about this? It seems a bug.

**Comment by Bambooin** [comment]
For the config issue, you can use: https://github.com/Bambooin/rimerc

We had improved the performance with hard work, you can try the latest version.
