### ISSUE TITLE
Every time new release breaks the old trime.yaml, and  even return it into the stock one.

### ISSUE THREAD

**Issue by amalgame21** [osfans/trime#952]
**Describe the bug**
Every time new release break trime.yaml.
Actually this is not the first time, which is just an easy fix (downgrade).
But this time it even return the `trime.yaml` into the stock one, which is unbearable to me.

This time is from 3.2.8 to 3.2.10 from F-Droid.

3 main Issues:
1) corner radius keeps 90 degree even round_corner is set to 14 (I just saw you updated it in #899)
2) background of candidate (right-hand-side blank area) always going to be white instead of black
![keyboard-layout-edited](https://user-images.githubusercontent.com/93383215/222980430-309ce126-0efc-46a6-9e7a-5599a92af14f.png)

The wiki is so ambiguous about the color of the code, it just simply list out all of them with no diagram explanation.
```
candidate_text_color: text_color
comment_text_color: candidate_text_color
border_color: back_color
candidate_separator_color: border_color
hilited_text_color: text_color
hilited_back_color: back_color
hilited_candidate_text_color: hilited_text_color
hilited_candidate_back_color: hilited_back_color
hilited_comment_text_color: comment_text_color
text_back_color: back_color
hilited_key_back_color: hilited_candidate_back_color
hilited_key_text_color: hilited_candidate_text_color
hilited_key_symbol_color: hilited_comment_text_color
hilited_off_key_back_color: hilited_key_back_color
hilited_on_key_back_color: hilited_key_back_color
hilited_off_key_text_color: hilited_key_text_color
hilited_on_key_text_color: hilited_key_text_color
key_back_color: back_color
key_border_color: border_color
key_text_color: candidate_text_color
key_symbol_color: comment_text_color
keyboard_back_color: border_color
label_color: candidate_text_color
off_key_back_color: key_back_color
off_key_text_color: key_text_color
on_key_back_color: hilited_key_back_color
on_key_text_color: hilited_key_text_color
preview_back_color: key_back_color
preview_text_color: key_text_color
shadow_color: border_color
``` 

Which code is belong to (2) ? I just forgot most of the configuration I did one year before. I want a good reference.

3) One year ago I spent at least twenty hours to study and configure the trime to make it work great in Android. After a long period of time (months) of untouched the rime folder, maybe I just update the app, today I want to do some mod because of 1) and 2) not working, I found out that the `trime.yaml` returned to the stock one. That means in this stage, I lost all the configuration. When I press `deploy` in the trime app, all the keyboard layout return to stock.

Luckily I have some spare phone also using trime which I sheldom upgrade, so I can transfer the whole old `rime` folder to this poor phone, and keep using the 3.2.8 version and every thing is fine.

**Expected behavior**
After update everything work properly

**Additional context**
I don't know whether you updated the parameters to make the color and the corner (I just saw you updated it in #899) not working as before or not. If it is the case, would you please to make a trime.yaml converter to update it to be compatible to the most updated version of the app? thanks.

**Comment by WhiredPlanck** [comment]
@amalgame21 Between version 3.2.8 and 3.2.10, I did a lot of refactoring on app theme parsing to speed up parsing and reduce redundant code. I did a lot of testing, and also let the community members (mainly members of the QQ Group) to help with the testing. I'm sorry I can't reproduce your issue, because these things work pretty well here.

But I still need to know some information, like: are you running the app on Android 12 or above? If so, I may need to take more time to investigate the true reason of breaking.

One thing I should tell you is the Wiki is not very usable since few people have time to update it. If you are able to speak Chinese, I'd like to invite you to join the QQ group (ID: 224230445) to ask the members for help.

**Comment by amalgame21** [comment]
Thanks for your great work actually.
Sorry that I did not test the most recent version before opening this issue, I just tested the most recent version on F-droid.
Now I tested with v3.2.11, everything seems working fine again.

However I find it annoying that when I uninstall the app and re-install another version, it will always replace the `trime.yaml` with the stock one. Would you consider making a prompt to ask the user whether replace the existing `trime.yaml` or not? thanks.

**Comment by amalgame21** [comment]
I found that when I disable the file permission, switch off the keyboard in setting, then enable the file permission again, and then open the trime app, after the app guided me to switch on the keyboard in setting, after all that the `trime.yaml` was automatically replaced with the stock one.

**Comment by WhiredPlanck** [comment]
@amalgame21 I always suggest users to install the latest version published on GitHub Release, even the latest version built by GitHub Actions. Because I don't own this repository and cannot control the PR merging and version release, the versions published in Release usually are buggy too.

Yes, every time new release will overwrite `trime.yaml` in the shared data directory[[1]](https://github.com/rime/home/wiki/SharedData) [[2]](https://github.com/rime/home/wiki/RimeWithSchemata#rime-%E4%B8%AD%E7%9A%84%E6%95%B8%E6%93%9A%E6%96%87%E4%BB%B6%E5%88%86%E4%BD%88%E5%8F%8A%E4%BD%9C%E7%94%A8), because it's the built-in data of app. The best practice is creating `trime.custom.yaml` in the user data directory, and the app will compile it with the stock `trime.yaml`, and output the final version in the build directory in the user data directory. For more detail about how this works, see [here](https://github.com/rime/home/wiki/CustomizationGuide).

**Comment by amalgame21** [comment]
Thanks for your advice!

**Comment by amalgame21** [comment]
@WhiredPlanck I finally noticed that the titles in this wiki page (https://github.com/osfans/trime/wiki/Rime经典资料汇总-菜鸟书评) are linked to those pages you adviced above. Since the hyperlink is on the title, I assumed that it was linked to other pages within this `trime` github page, so I did not click on it, instead I just browse all the URL links in the right column in the wiki page only, so I missed the most important part of it. 

If link to the pages outside the webpage, I think it is better show the full URL on that page so other user may know what they are clicking. Thanks.

**Comment by WhiredPlanck** [comment]
> @WhiredPlanck I finally noticed that the titles in this wiki page ([https://github.com/osfans/trime/wiki/Rime经典资料汇总-菜鸟书评](https://github.com/osfans/trime/wiki/Rime%E7%BB%8F%E5%85%B8%E8%B5%84%E6%96%99%E6%B1%87%E6%80%BB-%E8%8F%9C%E9%B8%9F%E4%B9%A6%E8%AF%84)) are linked to those pages you adviced above. Since the hyperlink is on the title, I assumed that it was linked to other pages within this `trime` github page, so I did not click on it, instead I just browse all the URL links in the right column in the wiki page only, so I missed the most important part of it.
> 
> If link to the pages outside the webpage, I think it is better show the full URL on that page so other user may know what they are clicking. Thanks.

Well, I usually make a reply on my laptop, so I can hover my mouse to see the real link. :smiley: Anyway, thanks for feedback.
